name: cupertino_sidebar
description: "Brings iOS-style sidebars and floating tab bars to Flutter, providing a sleek, native feel for iPadOS-style navigation in your app."
version: 1.0.1
repository: https://github.com/RoundedInfinity/cupertino_sidebar

screenshots:
  - description: A Sidebar displaying multiple locations.
    path: art/screenshot.png

topics:
  - widget
  - sidebar
  - cupertino
  - tabbar

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
