name: cupertino_sidebar
description: "A new Flutter package project."
version: 1.0.0
repository: https://github.com/RoundedInfinity/cupertino_sidebar

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
